services:
  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend/:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - 3001:3001
      
volumes:
  node_modules: