name: Build image and push to heroku
on:
  push:
    branches:
      - master
jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          run: npm run build-client

  build-push:
    runs-on: ubuntu-latest
    needs: build-client
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          healthcheck: https://trip-calculator-koodihaaste-21.herokuapp.com/api/v1/health
          checkstring: ok
          delay: 3
          rollbackonhealthcheckfailed: true
